#!/bin/sh
PATH=/opt/local/sbin:/opt/local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/bin
[ -e ./main ] || mkdir ./main
chown nobody ./main
exec setuidgid nobody multilog t s10485760 n5 '!tai64nlocal' ./main
